### ISSUE TITLE
Windows install requires the additional installation of punkt

### ISSUE THREAD

**Issue by SytanSD** [LAION-AI/natural_voice_assistant#15] opened 2024-02-15 03:22 UTC
Environment:
Windows 10 Pro - 10.0.19045 Build 19045
Python - 3.10.12 (as requested)
Conda Version - 23.5.2

Steps for Reproduction:
After full installation as directed, I tried to run [python main.py]
At this point, I get LookupError: Resource punkt not found.

Expected Behavior:
BUD-E should boot and function for conversation

Actual Behavior:
```Traceback (most recent call last):
  File "E:\BUD-E\natural_voice_assistant\main.py", line 175, in <module>
    main()
  File "E:\BUD-E\natural_voice_assistant\main.py", line 169, in main
    model = STT_LLM_TTS(device=device)
  File "E:\BUD-E\natural_voice_assistant\stt_llm_tts_model.py", line 371, in __init__
    self.tts = TTS(device=device)
  File "E:\BUD-E\natural_voice_assistant\stt_llm_tts_model.py", line 338, in __init__
    self.forward("warming up!")
  File "E:\BUD-E\natural_voice_assistant\stt_llm_tts_model.py", line 349, in forward
    wav = self.tts_model(text)
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\BUD-E\natural_voice_assistant\style_tts2_model.py", line 115, in forward
    ps = word_tokenize(ps[0])
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\nltk\tokenize\__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\nltk\tokenize\__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\nltk\data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\nltk\data.py", line 876, in _open
    return find(path_, path + [""]).open()
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\nltk\data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - 'C:\\Users\\Sytan/nltk_data'
    - 'C:\\Users\\Sytan\\miniconda3\\envs\\bud_e\\nltk_data'
    - 'C:\\Users\\Sytan\\miniconda3\\envs\\bud_e\\share\\nltk_data'
    - 'C:\\Users\\Sytan\\miniconda3\\envs\\bud_e\\lib\\nltk_data'
    - 'C:\\Users\\Sytan\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************
```
Additional Notes:

I did as the error told me and created my own .py file called installpunkt.py. After running it using the 2 lines suggested by the error, it installed punkt and allowed BUD-E to boot properly and begin listening/speaking

This issue could also likely be solved by running 
```
python.exe -c 'import nltk; nltk.download("punkt")'
```

**Comment by braunale** [comment] 2024-02-15 06:01
Hey @SytanSD, thanks for reporting this issue! I am familiar with this error and your as you said it can be simply fixed by calling 'nltk.download("punkt")'. However, this line is actually already added to the code (see **models_voice_assistant/TTS/style_tts2_model.py line 38**). It is executed whenever the voice assistant is started and should download 'punkt' if it is not found on you system. 
I will try to reproduce this.

**Comment by braunale** [comment] 2024-02-15 06:24
Hey @SytanSD I tried to reproduce your issue by removing by deleting the downloaded 'punkt' tokenizer which is usually stored in  C:\Users\[you username]\AppData\Roaming\nltk_data\tokenizers under Windows to force the download again. However for me it worked fine. When the TTS model is initialized, it realizes that 'punkt' is missing and then it starts the download automatically. Do you have any other suggestions on how I can reproduce the error or could you try to delete the punkt tokenizer at you system and try if it is downloaded now?   
![punkt_download](https://github.com/LAION-AI/natural_voice_assistant/assets/18556366/0bb9b74d-03f2-46b9-9aaa-6ee6f5fe9420)

**Comment by braunale** [comment] 2024-02-19 06:48
I will close this issue since I could not reproduce the error. Feel free to reopen if you encounter the problem again.

**Closed by braunale** 2024-02-19 06:48 UTC
